### ISSUE TITLE
RECAP 0.9.2.2 Not Working At All on Firefox

### ISSUE THREAD

**Issue by brianwc** [freelawproject/recap#133]
Ok, I'm actually on Debian Iceweasel 31.6.0, but we also have a report from a Windows 8.1 user on Firefox 37.0.2 reporting the same problem. The icon doesn't turn blue, it doesn't tell you whether the docket is available, it doesn't notify that docket is uploading, it doesn't upload documents. Nada.

**Comment by mlissner** [comment]
There was previously some code that was erroneously commented out that for
cookie verification. Since it was commented out our check for valid pacer
cookies was disabled.

I fixed that in the latest version, but I have a feeling that my fix
surfaced a change in pacer cookies that happened in the last couple years.

**Comment by mlissner** [comment]
Hm, we need more info here. At least one site is working fine for me: https://ecf.ilnd.uscourts.gov/cgi-bin/iquery.pl

Which one(s) are failing for you, @brianwc?

**Comment by brianwc** [comment]
Central District of California is one that is still broken. 
![cacd-2015-05-11](https://cloud.githubusercontent.com/assets/324921/7579937/835fee8e-f820-11e4-80d2-abff407b6408.png)

**Comment by brianwc** [comment]
Southern District of New York too:
![nysd-2015-05-11](https://cloud.githubusercontent.com/assets/324921/7579973/3c51a1f8-f821-11e4-94b9-7654feb6feb6.png)

**Comment by brianwc** [comment]
District of Massachusetts:
![mad-2015-05-11](https://cloud.githubusercontent.com/assets/324921/7579997/d094fdce-f821-11e4-940f-d3765d0fc5be.png)

**Comment by brianwc** [comment]
Even Northern District of Illinois:
![ilnd-2015-05-11](https://cloud.githubusercontent.com/assets/324921/7580068/9403716e-f822-11e4-9ce3-809e58003092.png)

Note that since this apparently worked for you, something is really weird here.

**Comment by mlissner** [comment]
What version of RECAP do you have?

**Comment by mlissner** [comment]
Oh, right, it's in the subject! That's the same version that's working for me. I'll try a few more of the examples you gave and see if they all work for me.

**Comment by mlissner** [comment]
OK, I went to each of the sites that you report as broken and they all work fine for me, which means we need to take this to the next level.

This will take you a moment, but I have no other ideas for figuring this out. First, this is the code that determines if you're on PACER:

```
if (cookie instanceof Components.interfaces.nsICookie && cookie.host.match("uscourts.gov")) {
    if (cookie.name.match("PacerUser") || cookie.name.match("PacerSession")) {
        if (cookie.value.indexOf("unvalidated") >= 0) {
            return false;
        } else {
           foundPacerUser = true;
        }
    }
}
```

For years this was accidentally commented out so that it always returned `true`. What this code does is check for a cookie from uscourts.gov that is named `PacerUser` or `PacerSession`. If either is found, it turns on RECAP. 

So, what we need to do is see what cookies you have when you're logged into PACER. To get that, please:
1. Log into PACER
2. Open up the JavaScript console in Firefox by pressing <kbd>Ctrl</kbd>+<kbd>Shift</kbd>+<kbd>K</kbd>. 
3. In the thing that pops up, at the bottom, paste the following JavaScript:
   
   ```
   function listCookies() {
       var theCookies = document.cookie.split(';');
       var aString = '';
       for (var i = 1 ; i <= theCookies.length; i++) {
           aString += i + ' ' + theCookies[i-1] + "\n";
       }
       return aString;
   }
   listCookies();
   ```
4. Email me the content of those cookies
5. **_Log out**_ (or else I'll be able to take control of your session using your cookies).

Once I have that info, hopefully I'll be able to see what's up.

If your cookies are all good, there are two other theories:
1. Another add-on is interfering with RECAP. (Solution: Create new profile, install RECAP and try it again. This is a fine idea anyway; you might as well do this too.)
2. I need to go up a level in the code to see if there's anything else that might make it not turn on properly. 

Let me know what you think, because it's working fine for me, but you're not alone on this one, so something is definitely going on.

**Comment by brianwc** [comment]
Starting a whole new profile with "firefox -P" and installing RECAP 0.9.2.2 and nothing else works. So, I think this means my existing firefox profile either has a conflicting extension or a messed up cookie situation. Should I proceed with the cookie investigation steps outlined above?

**Comment by mlissner** [comment]
That's good news. Yeah, do the cookie thing and then the next step is to figure out which of your add-ons is causing trouble. 

The usual way to do this is to disable half of them, restart the browser, test, then if it works re-enable half of the ones you disabled, or if it doesn't, disable another 50% of the remainder, etc. Eventually something will cause trouble, hopefully.

**Comment by mlissner** [comment]
The other person that reported this problem was going to pcl.uscourts.gov, which doesn't light up the extension because it's not a normal PACER URL.

Your issue seems to be a conflicting extension. If you want to continue debugging, let's check out your cookies or do the A/B extension tests I described above. One or the other should provide the answer, but since RECAP seems fine, I'm going to close this issue before I forget about it. As always, feel free to re-open if needed.
