### ISSUE TITLE
RECAP failing to upload dockets & documents

### ISSUE THREAD

**Issue by saizai** [freelawproject/recap#189]
See attached screenshots of console & network log.

Running on commit b678694415273b6df3049f247af7731c62da09e7.

![screen shot 2017-11-09 at 15 20 20](https://user-images.githubusercontent.com/40273/32613043-b6012284-c561-11e7-9446-99611afeae48.png)
![screen shot 2017-11-09 at 15 18 05](https://user-images.githubusercontent.com/40273/32613045-b62c5d6e-c561-11e7-8a7b-d7e85383d5bd.png)
![screen shot 2017-11-09 at 15 17 46](https://user-images.githubusercontent.com/40273/32613047-b7a3a670-c561-11e7-8931-924ff263ceab.png)
![screen shot 2017-11-09 at 15 17 38](https://user-images.githubusercontent.com/40273/32613049-b7cdcf90-c561-11e7-84ac-efade895eb79.png)
![screen shot 2017-11-09 at 15 14 15](https://user-images.githubusercontent.com/40273/32613050-b7f58774-c561-11e7-925a-09173045dd33.png)

**Comment by saizai** [comment]
Git pull'd to 40d24911d5d71748888d0ada03879651b97f6825, reloaded, tried again. Still no.
![screen shot 2017-11-09 at 15 20 20](https://user-images.githubusercontent.com/40273/32613410-c19970d2-c562-11e7-8fa8-928a59bad65f.png)

**Comment by saizai** [comment]
Manually calling functions doesn't seem to work either. And this.onDocumentViewSubmit does not appear to exist, contrary to the code.
![screen shot 2017-11-09 at 15 33 14](https://user-images.githubusercontent.com/40273/32613902-f3ee480e-c563-11e7-9def-d559d747b187.png)
![screen shot 2017-11-09 at 15 36 28](https://user-images.githubusercontent.com/40273/32613903-f411ec14-c563-11e7-8232-8c68fd97e2c6.png)
![screen shot 2017-11-09 at 15 36 53](https://user-images.githubusercontent.com/40273/32613904-f4385962-c563-11e7-8190-7cedc9adec5e.png)

**Comment by mlissner** [comment]
Thanks @saizai. I think this is fixed — it became an obvious issue when I tested this in Opera, but I think it was broken in Chrome too. Can you please pull to the latest?

**Comment by saizai** [comment]
Updated to 3c9c198a0ce4df4711a2b2fe8394983f8125a82a / v1.0.4.

Still failing for both dockets and documents uploads. :-/

Download tagging working just fine.


![screen shot 2017-11-10 at 11 47 02](https://user-images.githubusercontent.com/40273/32657660-7a42d0d2-c60e-11e7-806d-fa01446bede0.png)
![screen shot 2017-11-10 at 11 52 45](https://user-images.githubusercontent.com/40273/32657661-7a64e1b8-c60e-11e7-8cd8-19d262c2e4f5.png)
![screen shot 2017-11-10 at 11 54 47](https://user-images.githubusercontent.com/40273/32657662-7a9133f8-c60e-11e7-90a5-768f1ffa9f84.png)
![screen shot 2017-11-10 at 11 54 56](https://user-images.githubusercontent.com/40273/32657663-7abbe13e-c60e-11e7-947d-b69087487513.png)
![screen shot 2017-11-10 at 11 55 32](https://user-images.githubusercontent.com/40273/32657659-7a1112a4-c60e-11e7-810b-b514f8bf8964.png)
![screen shot 2017-11-10 at 11 56 38](https://user-images.githubusercontent.com/40273/32657688-90298e18-c60e-11e7-8e09-1afd12cde574.png)

**Comment by johnhawkinson** [comment]
I am confused what these screenshots are trying to show – a little more narrative might be helpful.

As far as I can tell the extension never tries to upload the document to CL. Not that it tries and fails.
And the certificate errors are completely unrelated.

So this is a logic problem?

What's the exact browser version and extension version?

**Comment by saizai** [comment]
I don't know where the problem is. Yes, as far as I can see, it never tries
to upload the document, though it does (successfully) insert links to
others' RECAP'd docs and dockets. I don't know why.

Yes, the cert errors are unrelated; they're just in the console log.

Chrome 62.0.3202.89 64bit
recap-chrome 3c9c198a0ce4df4711a2b2fe8394983f8125a82a

**Comment by mlissner** [comment]
Sai, can you please try: https://github.com/freelawproject/recap-chrome/commit/4e2d0331ff46520bf81ee70553fce4e3f6792e37 ? This is the last major bug, so I'd like to be sure that it's sussed out today. If it's possible, and if it's still broken, I'd love to get you in our Slack group so we can figure it out more quickly. I'm going to send you an invite now, just in case.

This is working for me on Chrome 61.

**Comment by saizai** [comment]
Git pulled to 4e2d0331ff46520bf81ee70553fce4e3f6792e37, reloaded, same behavior.

Got the Slack invite, see you there.

**Comment by mlissner** [comment]
I'm going to close this one out in lieu of #196.
